name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

      # Получаем код
      - name: Checkout
        uses: actions/checkout@v4


      # Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6'


      # Зависимости
      - name: Flutter pub get
        run: flutter pub get


      # Сборка Windows
      - name: Build Windows Release
        run: flutter build windows --release


      # Установка Inno Setup
      - name: Install Inno Setup
        run: |
          choco install innosetup -y


      # Создание установщика
      - name: Build Installer
        run: |
          iscc installer/RosTabak.iss


      # Загружаем готовый Setup.exe
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: RosTabak-Setup
          path: installer/output/RosTabak-Setup.exe
        
